### ISSUE TITLE
Bug: ApiToken secret is not cleaned up

### ISSUE THREAD

**Issue by Starefossen** [nais/unleasherator#108]
ApiToken secret is not cleaned up when the ApiToken is deleted. Most likely due to
missing controller reference.

**Comment by Starefossen** [comment]
https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/

**Comment by Starefossen** [comment]
How we do it for other resources: https://github.com/nais/unleasherator/blob/daeb2ffb1d5ac4bc79ca7230d0e6360a019b8b42/pkg/resources/unleash.go#L71

**Comment by Reasonable-Solutions** [comment]
We have two cases, one case for instanceSecrets that do have an controller reference since they live in the same namespace and one for the operatorInstanceSecrets who live in another namespace and thus cannot have a controller reference. 

I guess what we should do here is to add the apitoken-secret deletion to the finalizeroperations on the apitoken itself. Right?

**Comment by Starefossen** [comment]
The ApiToken secret can have a controller reference since it is stored in the same namespace as the ApiToken CRD resource itself.

What is needed in the finalizer operation is deleting the actual client from the Unleash instance.
